# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :mirror_actividad do |node|
    node.vm.box = "mirror"
    node.vm.network :private_network, ip: "192.168.33.11"
    node.vm.network "public_network", bridge: "enp5s0", ip:"192.168.131.121"
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "mirror-actividad" ]
    end
  end
end
